apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=users-db-service;Database=usersdb;Username=postgres;Password=postgres"
  Jwt__Key: "CHAVE_SUPER_SECRETA_MIN_32_CHARS!!"
  RabbitMQ__Password: "guest"
